In [105]:
import pandas as pd
import numpy as np
import zipfile, requests, io

In [106]:
""" modes function for table """

def mod_table(df) :
    modes = df.mode()
    return modes

In [107]:
""" read data URL """

path = "http://archive.ics.uci.edu/ml/machine-learning-databases/00368/Facebook_metrics.zip"

r = requests.get(path, stream=True)
z = zipfile.ZipFile(io.BytesIO(r.content))
file = z.extract('dataset_Facebook.csv')

data = pd.read_csv(file, sep = ';')

""" drop rows with NaN values """

data = data.dropna(0, how = 'any')

In [108]:
""" mean, max, min, median and mode for all data """

for col in list(data) :
    print(col, 'modes', data[col].mode(), "\n")

data.describe()

Page total likes modes 0    124940
dtype: int64

Type modes 0    Photo
dtype: object

Category modes 0    1
dtype: int64

Post Month modes 0    10
dtype: int64

Post Weekday modes 0    6
1    7
dtype: int64

Post Hour modes 0    3
dtype: int64

Paid modes 0    0.0
dtype: float64

Lifetime Post Total Reach modes 0      2232
1      2645
2      2938
3      3322
4      3358
5      3414
6      3528
7      3754
8      5280
9      5290
10     6692
11     9528
12    13544
13    32208
dtype: int64

Lifetime Post Total Impressions modes 0     4372
1     6503
2     7004
3     8533
4     8745
5    12735
dtype: int64

Lifetime Engaged Users modes 0    537
dtype: int64

Lifetime Post Consumers modes 0    182
1    298
2    319
3    322
4    335
5    374
6    482
7    503
8    513
9    642
dtype: int64

Lifetime Post Consumptions modes 0    431
1    513
2    599
3    652
4    719
5    730
6    795
7    889
dtype: int64

Lifetime Post Impressions by people who have liked your Page modes 0    1284
1    2541
2    2888
3    3675
4    4911
5    4935
6    5010
7    5732
dtype: int64

Lifetime Post reach by people who like your Page modes 0       690
1       704
2      1228
3      1640
4      1674
5      1722
6      2044
7      2124
8      2162
9      2174
10     2388
11     2426
12     2604
13     2616
14     2644
15     2660
16     2704
17     2752
18     2868
19     3114
20     3216
21     3230
22     3298
23     3768
24     5348
25     5372
26     7020
27     7800
28     8032
29     8120
30    20608
dtype: int64

Lifetime People who have liked your Page and engaged with your post modes 0    403
dtype: int64

comment modes 0    0
dtype: int64

like modes 0    98.0
dtype: float64

share modes 0    13.0
1    14.0
dtype: float64

Total Interactions modes 0    39
1    75
dtype: int64

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,495.000000,495.000000,495.000000,495.000000,495.000000,495.000000,495.000000,4.950000e+02,495.000000,495.000000,495.000000,4.950000e+02,495.000000,495.000000,495.000000,495.000000,495.000000,495.000000
mean,123173.268687,1.886869,7.028283,4.133333,7.844444,0.280808,14028.101010,2.985698e+04,926.830303,804.155556,1425.921212,1.691628e+04,6641.355556,614.135354,7.557576,179.145455,27.264646,213.967677
std,16203.818031,0.853268,3.304274,2.030735,4.385064,0.449849,22821.050008,7.714291e+04,987.713267,885.184440,2007.663460,6.007402e+04,7700.266455,614.346297,21.274384,324.412161,42.656388,381.677449
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.000000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.000000,0.000000,0.000000,0.000000
25%,112324.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3331.000000,5.798000e+03,399.000000,335.000000,512.500000,4.073500e+03,2213.000000,297.500000,1.000000,57.000000,10.000000,72.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5290.000000,9.084000e+03,630.000000,555.000000,861.000000,6.282000e+03,3478.000000,416.000000,3.000000,101.000000,19.000000,125.000000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13248.000000,2.250300e+04,1062.000000,969.000000,1479.000000,1.514300e+04,8018.000000,658.500000,7.000000,188.000000,32.500000,231.000000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.000000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.000000,5172.000000,790.000000,6334.000000

In [109]:
""" mode for each types """

modes = pd.DataFrame(data.groupby('Type').apply(mod_table)).fillna("")
modes

          Page total likes    Type Category Post Month Post Weekday Post Hour  \
Type
Link   0            138353    Link        1         12            6         3
       1
Photo  0            124940   Photo        1          4            7         3
       1                                             6
       2                                            10
       3
       4
       5
       6
       7
       8
       9
       10
       11
       12
       13
       14
       15
       16
       17
       18
       19
       20
       21
       22
       23
       24
       25
       26
Status 0            139441  Status        2         12            5        10
       1                                                          7
       2
       3
Video  0            137893   Video        1         11            2        11
       1                                                          3

          Paid Lifetime Post Total Reach Lifetime Post Total Impressions  \
Type
Link   0     0
       1
Photo  0     0                      2232                            4372
       1                            2938                            6503
       2                            3322                            7004
       3                            3358                            8533
       4                            3414                            8745
       5                            3528                           12735
       6                            3754
       7                            5280
       8                            5290
       9                            9528
       10                          32208
       11
       12
       13
       14
       15
       16
       17
       18
       19
       20
       21
       22
       23
       24
       25
       26
Status 0     0
       1
       2
       3
Video  0     1
       1

          Lifetime Engaged Users Lifetime Post Consumers  \
Type
Link   0                      66                     322
       1
Photo  0                     537                     298
       1                                             319
       2                                             335
       3                                             374
       4                                             482
       5                                             503
       6                                             513
       7                                             642
       8
       9
       10
       11
       12
       13
       14
       15
       16
       17
       18
       19
       20
       21
       22
       23
       24
       25
       26
Status 0
       1
       2
       3
Video  0
       1

          Lifetime Post Consumptions  \
Type
Link   0
       1
Photo  0                         431
       1                         513
       2                         599
       3                         652
       4                         719
       5                         730
       6                         795
       7                         889
       8
       9
       10
       11
       12
       13
       14
       15
       16
       17
       18
       19
       20
       21
       22
       23
       24
       25
       26
Status 0                        1692
       1
       2
       3
Video  0
       1

          Lifetime Post Impressions by people who have liked your Page  \
Type
Link   0
       1
Photo  0                                                1284
       1                                                2541
       2                                                2888
       3                                                3675
       4                                                4911
       5                                                4935
       6                                                5010
       7                                                5732
       8
       9
       10
       11
       12
       13
       14
       15
       16
       17
       18
       19
       20
       21
       22
       23
       24
       25
       26
Status 0
       1
       2
       3
Video  0
       1

          Lifetime Post reach by people who like your Page  \
Type
Link   0
       1
Photo  0                                               690
       1                                               704
       2                                              1228
       3                                              1640
       4                                              1674
       5                                              1722
       6                                              2044
       7                                              2124
       8                                              2162
       9                                              2174
       10                                             2388
       11                                             2426
       12                                             2604
       13                                             2616
       14                                             2644
       15                                             2660
       16                                             2704
       17                                             2752
       18                                             2868
       19                                             3114
       20                                             3216
       21                                             3230
       22                                             3298
       23                                             3768
       24                                             5348
       25                                             7800
       26                                            20608
Status 0
       1
       2
       3
Video  0
       1

          Lifetime People who have liked your Page and engaged with your post  \
Type
Link   0
       1
Photo  0                                                 403
       1
       2
       3
       4
       5
       6
       7
       8
       9
       10
       11
       12
       13
       14
       15
       16
       17
       18
       19
       20
       21
       22
       23
       24
       25
       26
Status 0
       1
       2
       3
Video  0
       1

          comment like share Total Interactions
Type
Link   0        0   12     2                 14
       1            32
Photo  0        0   79    14                 39
       1            98
       2
       3
       4
       5
       6
       7
       8
       9
       10
       11
       12
       13
       14
       15
       16
       17
       18
       19
       20
       21
       22
       23
       24
       25
       26
Status 0        2   86     1                117
       1        4   99    13                121
       2           129    18
       3           227    36
Video  0        2         13
       1       18

In [67]:
""" mean, max, min, median for each types """

data.groupby('Type').describe()

                Category  Lifetime Engaged Users  \
Type
Link   count   22.000000               22.000000
       mean     1.136364              342.818182
       std      0.467563              340.174414
       min      1.000000               24.000000
       25%      1.000000              105.000000
       50%      1.000000              244.000000
       75%      1.000000              422.000000
       max      3.000000             1374.000000
Photo  count  421.000000              421.000000
       mean     1.926366              825.368171
       std      0.884681              871.390487
       min      1.000000                9.000000
       25%      1.000000              421.000000
       50%      2.000000              612.000000
       75%      3.000000              951.000000
       max      3.000000            11452.000000
Status count   45.000000               45.000000
       mean     2.022222             2040.222222
       std      0.398228             1351.996838
       min      1.000000              128.000000
       25%      2.000000             1151.000000
       50%      2.000000             1701.000000
       75%      2.000000             2675.000000
       max      3.000000             6164.000000
Video  count    7.000000                7.000000
       mean     1.000000             1707.000000
       std      0.000000             1174.786080
       min      1.000000              459.000000
       25%      1.000000              829.000000
       50%      1.000000             1779.000000
       75%      1.000000             2090.500000
       max      1.000000             3872.000000

              Lifetime People who have liked your Page and engaged with your post  \
Type
Link   count                                          22.000000
       mean                                          210.545455
       std                                           188.873030
       min                                            19.000000
       25%                                            92.250000
       50%                                           161.500000
       75%                                           251.750000
       max                                           788.000000
Photo  count                                         421.000000
       mean                                          510.964371
       std                                           400.796595
       min                                             9.000000
       25%                                           305.000000
       50%                                           403.000000
       75%                                           570.000000
       max                                          3430.000000
Status count                                          45.000000
       mean                                         1719.844444
       std                                          1083.684581
       min                                           101.000000
       25%                                           995.000000
       50%                                          1604.000000
       75%                                          2256.000000
       max                                          4376.000000
Video  count                                           7.000000
       mean                                          979.428571
       std                                           650.805362
       min                                           363.000000
       25%                                           503.000000
       50%                                           885.000000
       75%                                          1192.000000
       max                                          2218.000000

              Lifetime Post Consumers  Lifetime Post Consumptions  \
Type
Link   count                22.000000                   22.000000
       mean                292.681818                  374.090909
       std                 291.385261                  358.404787
       min                  23.000000                   26.000000
       25%                  84.750000                  120.000000
       50%                 205.000000                  290.000000
       75%                 355.750000                  472.750000
       max                1106.000000                 1345.000000
Photo  count               421.000000                  421.000000
       mean                695.475059                 1310.334917
       std                 734.384315                 1974.750382
       min                   9.000000                    9.000000
       25%                 337.000000                  521.000000
       50%                 539.000000                  834.000000
       75%                 837.000000                 1336.000000
       max               11328.000000                19779.000000
Status count                45.000000                   45.000000
       mean               1949.555556                 2838.866667
       std                1319.980433                 2075.419548
       min                  86.000000                  112.000000
       25%                1073.000000                 1512.000000
       50%                1599.000000                 2201.000000
       75%                2567.000000                 3420.000000
       max                5934.000000                 9237.000000
Video  count                 7.000000                    7.000000
       mean               1584.714286                 2600.142857
       std                1160.701471                 2296.643524
       min                 411.000000                  539.000000
       25%                 763.000000                 1197.500000
       50%                1643.000000                 2331.000000
       75%                1845.500000                 2804.500000
       max                3822.000000                 7327.000000

              Lifetime Post Impressions by people who have liked your Page  \
Type
Link   count                                       2.200000e+01
       mean                                        1.114859e+04
       std                                         8.888569e+03
       min                                         2.307000e+03
       25%                                         6.367750e+03
       50%                                         9.034500e+03
       75%                                         1.390375e+04
       max                                         4.233800e+04
Photo  count                                       4.210000e+02
       mean                                        1.659465e+04
       std                                         6.486468e+04
       min                                         5.670000e+02
       25%                                         3.779000e+03
       50%                                         5.648000e+03
       75%                                         1.098700e+04
       max                                         1.107833e+06
Status count                                       4.500000e+01
       mean                                        1.866427e+04
       std                                         7.521069e+03
       min                                         5.009000e+03
       25%                                         1.388700e+04
       50%                                         1.750200e+04
       75%                                         2.210300e+04
       max                                         3.784900e+04
Video  count                                       7.000000e+00
       mean                                        4.314986e+04
       std                                         3.107268e+04
       min                                         2.143600e+04
       25%                                         2.564450e+04
       50%                                         3.013100e+04
       75%                                         4.584550e+04
       max                                         1.075020e+05

              Lifetime Post Total Impressions  Lifetime Post Total Reach  \
Type
Link   count                     2.200000e+01                  22.000000
       mean                      2.872545e+04               18544.590909
       std                       5.004205e+04               21399.411331
       min                       3.094000e+03                1536.000000
       25%                       6.861500e+03                3878.000000
       50%                       9.773000e+03                7422.000000
       75%                       2.615375e+04               30938.000000
       max                       2.297330e+05               70912.000000
Photo  count                     4.210000e+02                 421.000000
       mean                      2.930615e+04               13275.389549
       std                       8.138706e+04               22977.950816
       min                       5.700000e+02                 238.000000
       25%                       5.439000e+03                3110.000000
       50%                       8.198000e+03                4708.000000
       75%                       1.744200e+04               10844.000000
       max                       1.110282e+06              180480.000000
Status count                     4.500000e+01                  45.000000
       mean                      2.424447e+04               13078.888889
       std                       9.929143e+03                5218.086371
       min                       7.509000e+03                3930.000000
       25%                       1.709900e+04                9232.000000
       50%                       2.084900e+04               11096.000000
       75%                       3.051400e+04               15816.000000
       max                       5.996400e+04               31136.000000
Video  count                     7.000000e+00                   7.000000
       mean                      1.026224e+05               51205.714286
       std                       1.018383e+05               48825.191031
       min                       3.023500e+04               13544.000000
       25%                       3.618150e+04               19144.000000
       50%                       5.695000e+04               30624.000000
       75%                       1.408545e+05               68488.000000
       max                       2.771000e+05              139008.000000

              Lifetime Post reach by people who like your Page  \
Type
Link   count                                         22.000000
       mean                                        6544.363636
       std                                         5960.612461
       min                                         1180.000000
       25%                                         3156.000000
       50%                                         5039.000000
       75%                                         8140.000000
       max                                        27232.000000
Photo  count                                        421.000000
       mean                                        6118.539192
       std                                         7845.941764
       min                                          236.000000
       25%                                         2110.000000
       50%                                         3136.000000
       75%                                         5696.000000
       max                                        51456.000000
Status count                                         45.000000
       mean                                        9908.577778
       std                                         3997.608572
       min                                         2410.000000
       25%                                         7360.000000
       50%                                         8980.000000
       75%                                        11792.000000
       max                                        21352.000000
Video  count                                          7.000000
       mean                                       17386.285714
       std                                         9861.583607
       min                                         9568.000000
       25%                                        12340.000000
       50%                                        14112.000000
       75%                                        17312.000000
       max                                        38720.000000

              Page total likes        Paid   Post Hour  Post Month  \
Type
Link   count         22.000000   22.000000   22.000000   22.000000
       mean      116363.181818    0.272727    5.727273    6.590909
       std        21459.767350    0.455842    3.930126    4.563406
       min        85979.000000    0.000000    2.000000    1.000000
       25%        98829.250000    0.000000    3.000000    3.000000
       50%       115396.000000    0.000000    4.000000    4.500000
       75%       138059.000000    0.750000    9.250000   11.750000
       max       138895.000000    1.000000   14.000000   12.000000
Photo  count        421.000000  421.000000  421.000000  421.000000
       mean      122319.612827    0.282660    8.004751    6.790974
       std        16242.669134    0.450828    4.432561    3.228447
       min        81370.000000    0.000000    1.000000    1.000000
       25%       109670.000000    0.000000    3.000000    4.000000
       50%       128032.000000    0.000000    9.000000    7.000000
       75%       136013.000000    1.000000   11.000000   10.000000
       max       139441.000000    1.000000   23.000000   12.000000
Status count         45.000000   45.000000   45.000000   45.000000
       mean      132647.044444    0.222222    7.244444    9.066667
       std         7902.145290    0.420437    3.926342    2.553073
       min       104070.000000    0.000000    2.000000    3.000000
       25%       131300.000000    0.000000    3.000000    7.000000
       50%       135713.000000    0.000000    9.000000   10.000000
       75%       138353.000000    0.000000   10.000000   12.000000
       max       139441.000000    1.000000   15.000000   12.000000
Video  count          7.000000    7.000000    7.000000    7.000000
       mean      135014.857143    0.571429    8.714286    9.571429
       std         4730.551709    0.534522    4.347961    2.299068
       min       126424.000000    0.000000    2.000000    6.000000
       25%       132835.000000    0.000000    6.500000    8.000000
       50%       137893.000000    1.000000   11.000000   11.000000
       75%       138111.000000    1.000000   11.000000   11.000000
       max       138895.000000    1.000000   13.000000   12.000000

              Post Weekday  Total Interactions     comment         like  \
Type
Link   count     22.000000           22.000000   22.000000    22.000000
       mean       4.272727           89.045455    2.818182    73.318182
       std        1.856310           95.720564    3.633657    85.746240
       min        1.000000            6.000000    0.000000     5.000000
       25%        3.000000           32.750000    0.000000    19.500000
       50%        4.500000           52.500000    1.500000    37.000000
       75%        6.000000          125.000000    4.000000   110.750000
       max        7.000000          420.000000   15.000000   379.000000
Photo  count    421.000000          421.000000  421.000000   421.000000
       mean       4.087886          218.805226    7.581948   184.066508
       std        2.056203          407.568504   22.641009   346.542549
       min        1.000000            0.000000    0.000000     0.000000
       25%        2.000000           72.000000    1.000000    58.000000
       50%        4.000000          124.000000    3.000000   101.000000
       75%        6.000000          226.000000    7.000000   187.000000
       max        7.000000         6334.000000  372.000000  5172.000000
Status count     45.000000           45.000000   45.000000    45.000000
       mean       4.577778          217.044444    8.911111   176.711111
       std        1.924588          178.479940   12.451400   150.772499
       min        1.000000           17.000000    0.000000    13.000000
       25%        3.000000          106.000000    2.000000    86.000000
       50%        5.000000          186.000000    4.000000   150.000000
       75%        6.000000          265.000000   10.000000   226.000000
       max        7.000000         1009.000000   60.000000   859.000000
Video  count      7.000000            7.000000    7.000000     7.000000
       mean       3.571429          295.857143   12.285714   231.428571
       std        1.511858          183.992236    8.693183   142.025652
       min        2.000000           81.000000    2.000000    65.000000
       25%        2.500000          144.000000    4.000000   121.000000
       50%        3.000000          271.000000   17.000000   204.000000
       75%        4.500000          440.500000   18.000000   330.000000
       max        6.000000          550.000000   23.000000   449.000000

                   share
Type
Link   count   22.000000
       mean    12.909091
       std     11.751025
       min      0.000000
       25%      5.500000
       50%     10.500000
       75%     15.000000
       max     44.000000
Photo  count  421.000000
       mean    27.156770
       std     44.973104
       min      0.000000
       25%     10.000000
       50%     19.000000
       75%     32.000000
       max    790.000000
Status count   45.000000
       mean    31.422222
       std     24.272589
       min      1.000000
       25%     16.000000
       50%     28.000000
       75%     39.000000
       max    123.000000
Video  count    7.000000
       mean    52.142857
       std     42.643595
       min     13.000000
       25%     13.500000
       50%     44.000000
       75%     80.000000
       max    121.000000

In [104]:
""" the most popular """

dplc = data.duplicated()
print(dplc.unique())

[False]

In [ ]:
""" there aren't any duplicate rows at data table, so all objects in set are unique (there isn't popular object)"""